Creating Tensor

In [ ]:
import torch
my_first_Tensor = torch.tensor([10,20,30])
print(my_first_Tensor)

tensor([10, 20, 30])


In [ ]:
random_tensor = torch.rand(2,2)
print(random_tensor)

tensor([[0.8514, 0.0769],
        [0.7455, 0.4974]])


In [ ]:
zero_tensor = torch.zeros(2,2)
print(zero_tensor)

tensor([[0., 0.],
        [0., 0.]])


The Big 3 Properties

In [ ]:
print("Shape:",random_tensor.shape)

Shape: torch.Size([2, 2])


In [ ]:
print("Random Tensor:",random_tensor.dtype)

Random Tensor: torch.float32


In [ ]:
print("Random Tensor:",random_tensor.device)

Random Tensor: cpu


Basic Math (Element wise Operations)

In [ ]:
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([4,5,6])

added_tensors= tensor_a + tensor_b
print(added_tensors)

multiplied_tensors = tensor_a * tensor_b
print(multiplied_tensors)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [ ]:
import torch

print("--- SCENARIO 1: Crypto Price Aggregator ---\n")
# You are pulling live data from a Binance API aggregator for a quantitative trading algorithm.
# The tensor below represents a snapshot of the market.
# Rows = Assets (Row 0: BTC, Row 1: ETH, Row 2: SOL)
# Columns = Prices over the last 3 time steps (T1, T2, T3)

market_prices = torch.tensor([
    [95000.0, 95010.5, 95008.2],  # BTC
    [2800.0,  2805.1,  2802.9],   # ETH
    [145.2,   146.0,   145.8]     # SOL
])

# TODO 1: Extract ONLY the prices of ETH (the entire second row).
# Hint: Tensors are zero-indexed. You want row index 1, and all columns.
eth_prices = market_prices[1]
print(f"ETH Prices:\n{eth_prices}\n")

# TODO 2: Extract the LATEST price for all assets (the entire last column).
# Hint: You want all rows (:), but only the last column index.
latest_prices = market_prices[:,-1]
print(f"Latest Prices for all assets:\n{latest_prices}\n")


print("--- SCENARIO 2: YOLO Bounding Box Adjustments ---\n")
# You are preparing image data to run YOLO benchmarks.
# A bounding box is represented as [x_center, y_center, width, height].
# You have a tensor containing 2 bounding boxes for a single image.

boxes = torch.tensor([
    [100.0, 150.0, 50.0, 75.0],  # Box 1
    [200.0, 250.0, 30.0, 40.0]   # Box 2
])

# TODO 3: The input image was just scaled up by a factor of 2.
# Multiply the entire 'boxes' tensor by 2 so the coordinates match the new image resolution.
scaled_boxes = boxes * 2
print(f"Scaled Bounding Boxes:\n{scaled_boxes}\n")


print("--- SCENARIO 3: Reshaping Data ---\n")
# Sometimes APIs return data in a flat 1D sequence, but your neural network needs a 2D matrix.
# PyTorch uses `.view()` or `.reshape()` to change a tensor's shape without changing its data.

flat_data = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

# TODO 4: Reshape the 'flat_data' tensor into a 3x3 matrix.
# Hint: flat_data.view(rows, columns)
matrix_data = flat_data.reshape(3,3)
print(f"Reshaped 3x3 Matrix:\n{matrix_data}\n")

--- SCENARIO 1: Crypto Price Aggregator ---

ETH Prices:
tensor([2800.0000, 2805.1001, 2802.8999])

Latest Prices for all assets:
tensor([95008.2031,  2802.8999,   145.8000])

--- SCENARIO 2: YOLO Bounding Box Adjustments ---

Scaled Bounding Boxes:
tensor([[200., 300., 100., 150.],
        [400., 500.,  60.,  80.]])

--- SCENARIO 3: Reshaping Data ---

Reshaped 3x3 Matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])



In [ ]:
a = torch.ones(3, 3)
b = torch.tensor([1, 2, 3])
print(a+b)

tensor([[2., 3., 4.],
        [2., 3., 4.],
        [2., 3., 4.]])
